const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let z=30,windows=0,battery=72,energyProfile="Equilibrado",lang="es",accent="#6d5dfc";
const apps={
battery:{title:"Batería y energía",icon:"🔋",html:()=>`<h2>Batería y energía</h2><div class="batteryBig" id="batBig">--%</div><p class="muted" id="batState">Calculando...</p><div class="bar"><i id="batBar" style="width:72%"></i></div><div class="cards"><div class="card"><b>Tiempo estimado</b><h2 id="batTime">--</h2><small class="muted">según consumo actual</small></div><div class="card"><b>Salud</b><h2>Excelente</h2><small class="muted">Estado simulado del prototipo</small></div><div class="card"><b>Consumo</b><h2 id="batRate">-- W</h2><small class="muted">estimación dinámica</small></div></div><h3>Perfil de energía</h3><div class="profileGrid"><button class="profile" data-profile="Rendimiento">⚡<b> Rendimiento</b><small>Máxima potencia</small></button><button class="profile selected" data-profile="Equilibrado">◉<b> Equilibrado</b><small>Potencia y batería</small></button><button class="profile" data-profile="Ahorro de energía">🌿<b> Ahorro</b><small>Reduce consumo</small></button></div><h3>Consumo por aplicación</h3><div class="usageGrid"><div class="usage">🎮 Juegos <b>34%</b><div class="bar"><i style="width:34%"></i></div></div><div class="usage">🌐 Navegador <b>21%</b><div class="bar"><i style="width:21%"></i></div></div><div class="usage">⚙ Sistema <b>12%</b><div class="bar"><i style="width:12%"></i></div></div></div>`},
personal:{title:"Personalización",icon:"🎨",html:()=>`<h2>Personalización</h2><h3>Fondo de pantalla</h3><div class="themeGrid"><button class="theme dark" data-wall="dark">Aurora</button><button class="theme light" data-wall="light">Claro</button><button class="theme neon" data-wall="neon">Neón</button></div><p class="muted">También puedes usar fondos estáticos, presentaciones y fondos animados en una versión futura.</p><h3>Color de acento</h3><div class="themeGrid"><button class="theme" style="background:#6d5dfc" data-accent="#6d5dfc">Violeta</button><button class="theme" style="background:#18cfff" data-accent="#18cfff">Cian</button><button class="theme" style="background:#ff3d81" data-accent="#ff3d81">Rosa</button></div><h3>Escala de interfaz</h3><input id="scale" type="range" min="90" max="120" value="100"><span id="scaleVal">100%</span>`},
search:{title:"Búsqueda universal",icon:"⌕",html:()=>`<h2>Búsqueda universal</h2><p class="muted">Busca aplicaciones, archivos y contenido con lenguaje natural.</p><div class="globalSearch"><span>⌕</span><input id="uniInput" placeholder="Ejemplo: busca mis juegos o documentos de hoy"><button id="uniVoice">🎙</button></div><div id="uniResults"><div class="notice"><b>IA contextual</b><p>El prototipo puede clasificar resultados por aplicaciones, archivos y contenido. La indexación real del sistema y el aprendizaje de preferencias requieren integración con el sistema operativo.</p></div></div>`},
files:{title:"Explorador de archivos",icon:"📁",html:()=>`<h2>Inicio</h2><div class="cards"><div class="card">📁<h3>Documentos</h3><small class="muted">24 archivos</small></div><div class="card">🎮<h3>Juegos</h3><small class="muted">Biblioteca local</small></div><div class="card">☁️<h3>Nube</h3><small class="muted">Conectar almacenamiento</small></div></div><h3>Archivos recientes</h3><div class="files"><div class="file"><span>📄</span>Proyecto.html</div><div class="file"><span>🖼️</span>Fondo.png</div><div class="file"><span>📦</span>Juego.zip</div><div class="file"><span>📝</span>Notas.txt</div></div>`},
text:{title:"Editor de texto",icon:"📝",html:()=>`<h2>Editor RICAL</h2><textarea style="width:100%;height:70%;background:#060910;color:#fff;border:1px solid var(--line);border-radius:10px;padding:15px;outline:0" placeholder="Escribe aquí..."></textarea>`},
calendar:{title:"Calendario",icon:"📅",html:()=>`<h2>Calendario</h2><div class="hero"><h1 id="calendarDate"></h1><p>Planifica eventos y tareas.</p></div><div class="cards"><div class="card"><b>Hoy</b><p class="muted">Sin eventos programados.</p></div><div class="card"><b>Próximo evento</b><p class="muted">Puedes añadirlo en futuras versiones.</p></div></div>`},
media:{title:"RICAL Media",icon:"▶️",html:()=>`<h2>Reproductor multimedia</h2><div class="hero"><h1>Tu biblioteca multimedia</h1><p>Audio y vídeo.</p><input type="file" accept="audio/*,video/*" id="mediaFile"></div>`},
browser:{title:"RICAL Browser",icon:"🌐",html:()=>`<div class="globalSearch"><span>🌐</span><input id="url" value="https://sistemrical.local"><button id="go">Ir</button></div><div class="hero" id="browserPage"><h1>RICAL Browser</h1><p>Privacidad, pestañas y controles de navegación para la futura versión completa.</p></div>`},
webstudio:{title:"sistemRICAL Web Studio",icon:"</>",html:()=>`<div class="editor"><div class="code"><div class="tabs"><button class="active" data-tab="html">HTML</button><button data-tab="css">CSS</button><button data-tab="js">JS</button></div><textarea id="htmlCode"><h1>Hola, sistemRICAL</h1><p>Mi primera página.</p></textarea></div><div class="preview"><iframe id="preview"></iframe></div></div>`},
store:{title:"sistemRICAL Store",icon:"🎮",html:()=>`<div class="hero"><h1>sistemRICAL Store</h1><p>La futura tienda de juegos de sistemRICAL.</p></div><div class="gameGrid"><div class="game"><b>Próximamente</b><span class="muted">Juego destacado</span><button class="primary">Ver juego</button></div><div class="game"><b>Biblioteca</b><span class="muted">Tus juegos aparecerán aquí</span><button class="primary">Abrir</button></div><div class="game"><b>Novedades</b><span class="muted">Contenido nuevo</span><button class="primary">Explorar</button></div></div>`},
settings:{title:"Configuración",icon:"⚙️",html:()=>`<div class="settingsLayout"><nav class="settingsNav"><button class="active">Sistema</button><button>Personalización</button><button>Gaming</button><button>Red e Internet</button><button>Accesibilidad</button><button>Idioma y región</button><button>Privacidad</button></nav><main><h2>Sistema</h2><div class="row"><div><b>Modo Gaming</b><small class="muted">Prioriza juegos.</small></div><button class="toggle on">Activado</button></div><div class="row"><div><b>Actualizaciones</b><small class="muted">Buscar automáticamente.</small></div><button class="toggle on">Activado</button></div><div class="row"><div><b>Accesibilidad</b><small class="muted">Escala, fuentes y contraste.</small></div><button class="toggle">Desactivado</button></div></main></div>`},
terminal:{title:"Terminal",icon:"⌘",html:()=>`<div class="term"><div>sistemRICAL Terminal v1.0</div><div>Escribe help para ver comandos.</div><div id="termOut"></div><div>user@sistemRICAL:~$ <input id="termInput" autofocus></div></div>`},
about:{title:"Acerca de sistemRICAL",icon:"ⓘ",html:()=>`<div class="about"><div class="bootR">R</div><h1>sistemRICAL OS</h1><p class="muted">Sistema de escritorio gaming y creativo.</p><p>Versión de prototipo 0.2</p></div>`}
};
function closePanels(){$$(".panel").forEach(x=>x.classList.remove("open"))}
function openApp(k){const a=apps[k];if(!a)return;const w=document.createElement("div");w.className="window";w.style.zIndex=++z;w.innerHTML=`<div class="titlebar"><b>${a.icon}　${a.title}</b><button class="wbtn min">—</button><button class="wbtn max">□</button><button class="wbtn close">×</button></div><div class="body">${a.html()}</div>`;$("#windows").appendChild(w);w.querySelector(".close").onclick=()=>w.remove();w.querySelector(".min").onclick=()=>w.style.display="none";w.querySelector(".max").onclick=()=>w.classList.toggle("max");w.onmousedown=()=>w.style.zIndex=++z;closePanels();afterApp(k,w)}
function afterApp(k,w){if(k==="battery"){updateBattery();w.querySelectorAll(".profile").forEach(b=>b.onclick=()=>{energyProfile=b.dataset.profile;w.querySelectorAll(".profile").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");updateBattery()})}if(k==="personal"){w.querySelectorAll("[data-accent]").forEach(b=>b.onclick=()=>setAccent(b.dataset.accent));w.querySelector("#scale").oninput=e=>{document.documentElement.style.fontSize=e.target.value+"%";w.querySelector("#scaleVal").textContent=e.target.value+"%"};w.querySelectorAll("[data-wall]").forEach(b=>b.onclick=()=>setWall(b.dataset.wall))}if(k==="search")setupUniversal(w);if(k==="webstudio")setupStudio(w);if(k==="browser")w.querySelector("#go").onclick=()=>w.querySelector("#browserPage").innerHTML="<h1>"+w.querySelector("#url").value.replace(/[<>&]/g,"")+"</h1><p class='muted'>Vista de demostración del navegador.</p>";if(k==="terminal")setupTerminal(w);if(k==="calendar")w.querySelector("#calendarDate").textContent=new Date().toLocaleDateString("es-PE",{weekday:"long",day:"numeric",month:"long",year:"numeric"});w.querySelectorAll(".toggle").forEach(b=>b.onclick=()=>{b.classList.toggle("on");b.textContent=b.classList.contains("on")?"Activado":"Desactivado"})}
function setupUniversal(w){const i=w.querySelector("#uniInput"),r=w.querySelector("#uniResults");i.oninput=()=>{const q=i.value.toLowerCase();r.innerHTML=q?`<div class="notice"><b>Resultados para “${q.replace(/[<>&]/g,"")}”</b><p>Aplicaciones relacionadas · archivos recientes · contenido indexado.</p></div>`:""}}
function setupStudio(w){const html=w.querySelector("#htmlCode"),frame=w.querySelector("#preview");function render(){frame.srcdoc=html.value}html.oninput=render;render()}
function setupTerminal(w){const i=w.querySelector("#termInput"),o=w.querySelector("#termOut");i.onkeydown=e=>{if(e.key!=="Enter")return;let c=i.value.trim().toLowerCase(),r="";if(c==="help")r="help, date, system, battery, store, settings, clear, reboot";else if(c==="date")r=new Date().toString();else if(c==="system")r="sistemRICAL OS 0.2 | Gaming Desktop";else if(c==="battery")r="Batería: "+battery+"% | Perfil: "+energyProfile;else if(c==="store")openApp("store");else if(c==="settings")openApp("settings");else if(c==="clear")o.innerHTML="";else if(c==="reboot")location.reload();else if(c)r="Comando no encontrado: "+c;if(r){let d=document.createElement("div");d.textContent=r;o.appendChild(d)}i.value=""}}
function setAccent(c){document.documentElement.style.setProperty("--accent",c);accent=c}
function setWall(w){const bg={dark:"radial-gradient(circle at 75% 20%,#31527f,transparent 30%),linear-gradient(135deg,#070b14,#111a32)",light:"linear-gradient(135deg,#dce5f1,#94a7c2)",neon:"radial-gradient(circle at 70% 30%,#7b00ff55,transparent 35%),linear-gradient(135deg,#10051c,#032c35)"}[w];document.querySelector(".wallpaper").style.background=bg}
function updateBattery(){const rate=energyProfile==="Rendimiento"?18:energyProfile==="Ahorro de energía"?6:11;const mins=Math.round(battery*60/rate);const b=$("#batBig");if(b)b.textContent=battery+"%";const bar=$("#batBar");if(bar)bar.style.width=battery+"%";const state=$("#batState");if(state)state.textContent=energyProfile+" · consumo estimado "+rate+" W";const t=$("#batTime");if(t)t.textContent=Math.floor(mins/60)+" h "+mins%60+" min";const br=$("#batRate");if(br)br.textContent=rate+" W";$("#miniBattery").textContent=battery+"%";$("#miniBatteryState").textContent=energyProfile}
function tick(){const d=new Date();$("#clock").textContent=d.toLocaleTimeString("es-PE",{hour:"2-digit",minute:"2-digit"})+"  "+d.toLocaleDateString("es-PE",{day:"2-digit",month:"2-digit"});$("#miniBattery").textContent=battery+"%";$("#batteryIcon").textContent=battery>70?"▰":battery>30?"▰":"▱"}tick();setInterval(tick,1000);
const desk=[["battery","🔋","Batería"],["personal","🎨","Personalización"],["search","⌕","Búsqueda IA"],["files","📁","Archivos"],["text","📝","Editor"],["calendar","📅","Calendario"],["media","▶️","Media"],["browser","🌐","Browser"],["webstudio","</>","Web Studio"],["store","🎮","Store"],["settings","⚙️","Configuración"],["terminal","⌘","Terminal"]];
desk.forEach(a=>{let b=document.createElement("button");b.className="deskIcon";b.innerHTML='<span class="ico">'+a[1]+'</span><small>'+a[2]+'</small>';b.onclick=()=>openApp(a[0]);$("#deskIcons").appendChild(b);let p=document.createElement("button");p.className="task";p.textContent=a[1];p.title=a[2];p.onclick=()=>openApp(a[0]);if(["store","files","webstudio","browser"].includes(a[0]))$("#pinned").appendChild(p)});
Object.entries(apps).forEach(([k,a])=>{let b=document.createElement("button");b.dataset.app=k;b.innerHTML='<span class="appIcon">'+a.icon+'</span><small>'+a.title+'</small>';b.onclick=()=>openApp(k);$("#appGrid").appendChild(b)});
$("#startBtn").onclick=()=>$("#startMenu").classList.toggle("open");$("#controlBtn").onclick=()=>$("#control").classList.toggle("open");$("#searchBtn").onclick=()=>{openApp("search")};$("#powerBtn").onclick=()=>location.reload();$$("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close).classList.remove("open"));$$("[data-toggle]").forEach(b=>b.onclick=()=>b.classList.toggle("on"));$("#volume").oninput=e=>$("#volumeVal").textContent=e.target.value+"%";$("#voiceBtn").onclick=()=>{if("webkitSpeechRecognition"in window){const r=new webkitSpeechRecognition();r.lang="es-PE";r.onresult=e=>$("#searchInput").value=e.results[0][0].transcript;r.start()}else alert("El reconocimiento de voz depende del navegador.")};$("#searchInput").oninput=e=>{const q=e.target.value.toLowerCase();$$(".appGrid button").forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q)?"block":"none")};
if("getBattery"in navigator)navigator.getBattery().then(b=>{battery=Math.round(b.level*100);b.addEventListener("levelchange",()=>{battery=Math.round(b.level*100);updateBattery()});updateBattery()});else updateBattery();
setTimeout(()=>{$("#boot").remove();$("#desktop").hidden=false},1200);