const $=s=>document.querySelector(s);
const apps={
store:["sistemRICAL Store",'<div class="store-banner"><h1>sistemRICAL Store</h1><p>Tu futura tienda de juegos. Pronto podrás descubrir, comprar y organizar tus juegos aquí.</p></div><div class="game-grid"><div class="game"><b>Próximamente</b><span class="muted">Juegos destacados</span><button>Ver catálogo</button></div><div class="game"><b>Tu biblioteca</b><span class="muted">Tus juegos en un solo lugar</span><button>Abrir</button></div><div class="game"><b>Novedades</b><span class="muted">Próximas funciones</span><button>Explorar</button></div></div>'],
explorer:["Explorador de archivos",'<div class="file-layout"><aside class="sidebar"><button>⌂ Inicio</button><button>◫ Escritorio</button><button>▣ Documentos</button><button>▤ Descargas</button><button>◉ Este equipo</button></aside><main><h2>Acceso rápido</h2><div class="files"><div class="file"><span>📁</span>Documentos</div><div class="file"><span>🎮</span>Juegos</div><div class="file"><span>🖼</span>Imágenes</div><div class="file"><span>📥</span>Descargas</div><div class="file"><span>📄</span>README.txt</div><div class="file"><span>💾</span>Disco local</div></div></main></div>'],
settings:["Configuración",'<div class="settings-grid"><aside class="settings-nav"><button class="active">Sistema</button><button>Personalización</button><button>Aplicaciones</button><button>Red e Internet</button><button>Gaming</button><button>Privacidad</button></aside><main><h2>Sistema</h2><p class="muted">Personaliza tu experiencia de sistemRICAL.</p><div class="setting-row"><div><b>Modo de rendimiento</b><div class="muted">Prioriza juegos y aplicaciones.</div></div><button class="toggle on">Activado</button></div><div class="setting-row"><div><b>Animaciones</b><div class="muted">Efectos visuales del escritorio.</div></div><button class="toggle on">Activado</button></div><div class="setting-row"><div><b>Modo oscuro</b><div class="muted">Interfaz oscura del sistema.</div></div><button class="toggle on">Activado</button></div></main></div>'],
terminal:["Terminal",'<div class="terminal" id="terminalBox"><div>sistemRICAL Terminal v1.0</div><div>Escribe help para ver los comandos.</div><div id="termOutput"></div><label>user@sistemRICAL:~$ <input id="termInput" class="term-input" autocomplete="off"></label></div>'],
browser:["RICAL Browser",'<div class="browserbar"><input id="urlInput" value="https://sistemrical.local"><button id="goUrl">Ir</button></div><div class="browser-content" id="browserContent"><h1>RICAL Browser</h1><p class="muted">Panel de navegador de demostración. La navegación web real requiere integrar un servicio externo.</p></div>'],
about:["Acerca de sistemRICAL",'<div class="about"><div class="bigR">R</div><h1>sistemRICAL</h1><p class="muted">Un escritorio digital diseñado para jugar, crear y trabajar.</p><p>Versión 0.1 • Interfaz web experimental</p></div>']
};
let count=0;
function closePanels(){["startMenu","notificationCenter","searchOverlay"].forEach(id=>{const el=document.getElementById(id);if(el)el.classList.remove("open")})}
function openApp(key){const app=apps[key];if(!app)return;const host=$("#windows");if(!host)return;
const w=document.createElement("div");w.className="window";w.style.zIndex=40+(++count);w.innerHTML='<div class="titlebar"><b>'+app[0]+'</b><button class="win-btn min">—</button><button class="win-btn max">□</button><button class="win-btn close">×</button></div><div class="win-body">'+app[1]+'</div>';host.appendChild(w);
w.querySelector(".close").onclick=()=>w.remove();w.querySelector(".min").onclick=()=>w.style.display="none";w.querySelector(".max").onclick=()=>w.classList.toggle("max");w.onmousedown=()=>w.style.zIndex=40+(++count);
if(key==="terminal")setupTerminal(w);if(key==="browser")setupBrowser(w);if(key==="settings")w.querySelectorAll(".toggle").forEach(b=>b.onclick=()=>{b.classList.toggle("on");b.textContent=b.classList.contains("on")?"Activado":"Desactivado"});
closePanels()}
function setupTerminal(w){const input=w.querySelector("#termInput"),out=w.querySelector("#termOutput");input.focus();input.addEventListener("keydown",e=>{if(e.key!=="Enter")return;const cmd=input.value.trim().toLowerCase();const line=document.createElement("div");let text="";if(cmd==="help")text="Comandos: help, date, system, store, settings, clear, reboot";else if(cmd==="date")text=new Date().toString();else if(cmd==="system")text="sistemRICAL 0.1 | Escritorio gaming | Estado: funcionando";else if(cmd==="store")openApp("store");else if(cmd==="settings")openApp("settings");else if(cmd==="reboot")location.reload();else if(cmd==="clear"){out.innerHTML="";input.value="";return}else if(cmd)text="Comando no encontrado: "+cmd;line.textContent=text;out.appendChild(line);input.value=""})}
function setupBrowser(w){w.querySelector("#goUrl").onclick=()=>{const target=w.querySelector("#urlInput").value;w.querySelector("#browserContent").innerHTML="<h2>"+target.replace(/[&<>]/g,"")+"</h2><p class='muted'>Esta es una vista de demostración, no una conexión web real.</p>"}}
document.querySelectorAll("[data-open]").forEach(b=>b.addEventListener("click",()=>openApp(b.dataset.open)));
const start=$("#startBtn");if(start)start.onclick=()=>{$("#startMenu").classList.toggle("open");$("#notificationCenter").classList.remove("open")};
const closeStart=$("#closeStart");if(closeStart)closeStart.onclick=()=>$("#startMenu").classList.remove("open");
const notify=$("#notifyBtn");if(notify)notify.onclick=()=>{$("#notificationCenter").classList.toggle("open");$("#startMenu").classList.remove("open")};
const search=$("#searchBtn");if(search)search.onclick=()=>{$("#searchOverlay").classList.toggle("open");$("#globalSearch").focus()};
const power=$("#powerBtn");if(power)power.onclick=()=>location.reload();
document.querySelectorAll(".quick").forEach(b=>b.onclick=()=>b.classList.toggle("active"));
const global=$("#globalSearch");if(global)global.addEventListener("input",()=>{const result=$("#searchResults");result.innerHTML="";Object.keys(apps).filter(k=>(apps[k][0]+" "+k).toLowerCase().includes(global.value.toLowerCase())).forEach(k=>{const d=document.createElement("div");d.className="result";d.textContent=apps[k][0];d.onclick=()=>openApp(k);result.appendChild(d)})});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closePanels();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){$("#searchOverlay").classList.add("open");$("#globalSearch").focus()}});
function tick(){const c=$("#clock");if(c)c.textContent=new Date().toLocaleTimeString("es-PE",{hour:"2-digit",minute:"2-digit"})}tick();setInterval(tick,1000);
setTimeout(()=>{const b=$("#boot"),d=$("#desktop");if(b)b.classList.add("hidden");if(d)d.classList.remove("hidden")},1400);
